version: '3.8'

services:
  # 1. PostgreSQL - Clan Service İçin
  clanservice-db:
    image: postgres:latest
    container_name: clanservice-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clanservicedb
    ports:
      - "5432:5432"
    volumes:
      - clan_pg_data:/var/lib/postgresql

  # 2. PostgreSQL - Identity Service İçin
  identity-db:
    image: postgres:latest
    container_name: identity-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: IdentityDb
    ports:
      - "5433:5432" 
    volumes:
      - identity_pg_data:/var/lib/postgresql

  # 3. MongoDB - Message Service İçin
  message-db:
    image: mongo:latest
    container_name: message-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - "27017:27017"
    volumes:
      - message_mongo_data:/data/db

volumes:
  clan_pg_data:
  identity_pg_data:
  message_mongo_data: