// <auto-generated />
using System;
using ClanService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClanService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250213105224_UpdateUserModel")]
    partial class UpdateUserModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("ClanService.Models.Channel", b =>
                {
                    b.Property<Guid>("ChannelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClanId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ChannelId");

                    b.HasIndex("ClanId");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("ClanService.Models.Clan", b =>
                {
                    b.Property<Guid>("ClanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ClanId");

                    b.ToTable("Clans");
                });

            modelBuilder.Entity("ClanService.Models.ClanMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClanId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClanId");

                    b.HasIndex("UserId");

                    b.ToTable("ClanMemberships");
                });

            modelBuilder.Entity("ClanService.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ClanService.Models.VoiceChannel", b =>
                {
                    b.Property<Guid>("VoiceChannelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClanId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("VoiceChannelId");

                    b.HasIndex("ClanId");

                    b.ToTable("VoiceChannels");
                });

            modelBuilder.Entity("ClanService.Models.Channel", b =>
                {
                    b.HasOne("ClanService.Models.Clan", "Clan")
                        .WithMany("Channels")
                        .HasForeignKey("ClanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clan");
                });

            modelBuilder.Entity("ClanService.Models.ClanMembership", b =>
                {
                    b.HasOne("ClanService.Models.Clan", "Clan")
                        .WithMany("ClanMemberShips")
                        .HasForeignKey("ClanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClanService.Models.User", "User")
                        .WithMany("ClanMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClanService.Models.VoiceChannel", b =>
                {
                    b.HasOne("ClanService.Models.Clan", "Clan")
                        .WithMany("VoiceChannels")
                        .HasForeignKey("ClanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clan");
                });

            modelBuilder.Entity("ClanService.Models.Clan", b =>
                {
                    b.Navigation("Channels");

                    b.Navigation("ClanMemberShips");

                    b.Navigation("VoiceChannels");
                });

            modelBuilder.Entity("ClanService.Models.User", b =>
                {
                    b.Navigation("ClanMemberships");
                });
#pragma warning restore 612, 618
        }
    }
}
